---
title: "Perception of pain analyses"
author: "Daniel Elmstrom Christensen"
date: "05/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(Sentida)
library(remotes)
remotes::install_github("Guscode/Sentida", force = T)
library(Sentida)

b1 = sentida("Det var en varm og dejlig solskinsdag, jeg var lige kommet hjem og havde krammet min dejlige kæreste, da jeg fik det mest fortryllende kys nogensinde")


b2 = sentida("Jeg flirter lidt med den dejlige mand jeg har mødt. Jeg kan simpelthen ikke lade være, han er helt og aldeles himmelsk, og så har han den sødeste og mest trofaste hund.", "mean")

b3 = sentida("En af de mest opfriskende minder, som gang på gang gør mig lykkelig. Er af min søde og dejlige lille niece, der gynger ude i haven på en varm solskinsdag")

p1 = sentida("Jeg kom ind på hospitalet, det var forfærdeligt. Min arm var blevet skoldet og smerten blev ved med at føltes varm og sviende, det havde været en grusom oplevelse.")


n1 = sentida("Jeg skulle bo på et klassisk hotel, mens mit almindelige hus blev renoveret. Hotellet var rødt og blev bygget i 1999, og har udsigt ud over den enorme by.")

p2 = sentida("Mit hjerte bankede og jeg havde en frygtelig tom fornemmelse i maven efter den grufulde og ødelæggende oplevelse. Det var forfærdeligt og jeg følte mig kvalt i situationen.")

p3 = sentida("Smerten føltes jagende og sviende, da jeg vågnede op midt i operationen. De var igang med at skære mit venstre bryst op. Jeg frygtede for livet - tænkte at de ville dræbe mig.")

n2 = sentida("Samtalen hos den foreløbige chef, havde været lang og vi snakkede kun om officielle emner, som ikke påvirkede borgerne. De lange samtaler var ved at blive dagligdag for mig.")

n3 = sentida("Jeg havde altid været lav og tynd i hele gymnasietiden, men efter at jeg havde været ude på den lange internationale rejse, var der sket en klar ændring.")

list = c(b1,b2,b3,n1,n2,n3,p1,p2,p3)

View(list)
(b1+b2+b3)/3
(n1+n2+n3)/3
(p1+p2+p3)/3


17*0.04


?lme4
```

```{r}
#Read csv
data <- read.csv("Bedøm ord.csv")
#Invert df
df <- data.frame(t(data[-1]))
df$word_frequency = c(50, 2190,7101, 1445, 51316, 161, 133, 5961, 3994, 5000, 36, 4776, 288, 9673, 4832, 46351, 3531, 302, 1735, 1119, 4299, 3907, 558, 15520, 1199, 357, 1411, 8576, 4417, 3554, 6959, 2786, 2757, 8311, 6441, 501, 7751, 902, 3747, 1456, 634, 153, 28591, 4456, 1021, 241, 2033, 1846, 37880, 3897, 8025, 4478, 117, 374, 497, 5560, 10956, 651, 6333, 5478)

```

```{r}
#Add median
df$median_score<- apply(df[,2:28],1, median, na.rm = TRUE)

#Add SD
df$standard_deviation <- round(apply(df[,2:28],1, sd, na.rm = TRUE),2)

#Add rownames to a column
df <- setDT(df, keep.rownames = TRUE)[]
```

```{r}

write.csv(df, file ="cogcom.csv")



#filter by SD
df <- filter(df, df$sd<1.3)

#Filter by Pain related
df_pain <- filter(df_new, median>=7)

df = filter(df, df$median != 6)

#Filter by Neutral related
df_neutral <- filter(df_new, median < 6)
df_neutral <- filter(df_neutral, median > 4)

#Filter by Comfortable related
df_comfortable <- filter(df_new, median<=3)


df = filter(df, df$rn != "Behagelig")

df$stim = ifelse(df$median <= 3, "com", "neut")
df$stim = ifelse(df$median >= 7 , "painful", df$stim)

t.test(q$freq, df_pain$freq)

summary(aov(df$freq ~ df$stim))

pairwise.t.test(df$freq, df$stim, p.adjust.method = "bonf")

mean(df_neutral$freq)
mean(df_pain$freq)
mean(q$freq)

mp = mean(df_pain$median)
psd = mean(df_pain$sd)

x=seq(-4,4,length=200)
y=1/sqrt(2*pi*psd^2)*exp((-x-mp)^2/2*psd^2)

curve(1/sqrt(2*pi*psd^2)*exp(-(x-mp)^2/2*psd^2),from=-3, to=12, col = "red")

par(new=TRUE)
curve(1/sqrt(2*pi*sdn^2)*exp(-(x-mn)^2/2*sdn^2),from=-3, to=12, col = "blue")

curve(1/sqrt(2*pi*sdc^2)*exp(-(x-mc)^2/2*sdc^2),from=-3, to=12, col = "green")

curve(3.1+0.58*x, col = "blue", from = -2, to = 2)
par(new=TRUE)
curve(2.66+0.58*x, col =  "red",from = -2, to = 2)

curve(3.1+0.12+0.58*x, col = "green", from = -2, to = 2)

plot(x,3.1+0.12+0.58*x)
par(new=TRUE)
plot(x,3.1-0.44+0.58*x)


ggplot(df, aes(df$X1))+geom_histogram()



mn = mean(df_neutral$median)
sdn = mean(df_neutral$sd)


mc = mean(df_comfortable$median)
sdc = mean(df_comfortable$sd)




mean(df_pain$freq)
mean(df_neutral$freq)
mean(df_comfortable$freq)

sd(df_pain$freq)
sd(df_neutral$freq)
sd(df_comfortable$freq)

t.test(df_pain$freq, df_comfortable$freq)
t.test(q$freq, df_comfortable$freq)

t.test(df_pain$freq, df_neutral$freq)



summary(aov(df_neutral$freq ~ df_pain$freq + q$freq))

pairwise.t.test(df_pain$freq, q$freq, p.adjust.method = "bonf")

?pairwise.t.test()


m1 = aov(df_pain$freq ~ q$freq)
summary(m1)

data = as.data.frame(c(df_pain, q, df_neutral))

df <- data.frame(t(data[-1]))



ggplot()

anova_apa(m1)

install.packages("ez")
library(ez)
plot(m1)
?aov()

q = filter(df_comfortable, df_comfortable$sd < 1.14)

df$freq = c(50, 2190,7101, 1445, 51316, 161, 133, 5961, 3994, 5000, 36, 4776, 288, 9673, 4832, 46351, 3531, 302, 1735, 1119, 4299, 3907, 558, 15520, 1199, 357, 1411, 8576, 4417, 3554, 6959, 2786, 2757, 8311, 6441, 501, 7751, 902, 3747, 1456, 634, 153, 28591, 4456, 1021, 241, 2033, 1846, 37880, 3897, 8025, 4478, 117, 374, 497, 5560, 10956, 651, 6333, 5478)


```

