---
title: "portfolio 3"
author: "Jesper"
date: "7/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(pastecs)
library(WRS2)
library(stringi)
library(stringr)
library(anytime)
```


```{r}

files <- list.files(path = "data",
                    pattern = ".csv",
                    full.names = T)  

data <- lapply(files, read_csv) %>% 
  plyr::rbind.fill()  

data$Gender = as.factor(data$Gender)
data$Condition = as.factor(data$Condition)

str(data$Condition)
str(data$Gender)

database = read.csv("MRC_database.csv")

data$wordclean = toupper(data$Word)

View(data)

# rename the capitalized column to "word"
colnames(data)[colnames(data) == "wordclean"] = "word"

merged = merge(data, database, by = "word")

View(merged)






merged$Reaction_timez = (merged$Reaction_time-mean(merged$Reaction_time))/(sd(merged$Reaction_time))

ggplot(merged, aes(merged$Reaction_timez))+geom_histogram()

#removing them over 3

merged1 = filter(merged, merged$Reaction_timez < 3)

ggplot(merged1, aes(merged1$Reaction_timez))+geom_histogram()


#putting the z-score back to normal values.
merged1$Reaction_time2 = merged1$Reaction_timez*sd(merged$Reaction_time)+mean(merged$Reaction_time)

ggplot(merged1, aes(merged1$Reaction_time2))+geom_histogram()




View(merged)

cor.test(merged1$Reaction_time2, merged1$kf_freq, method = "spearman")


ggplot(merged1, aes(merged1$Reaction_time, 
                  merged1$kf_freq))+geom_point()+geom_smooth(method = "lm")


ggplot(merged1, aes(log(merged1$nlet)))+geom_histogram()


ggplot(merged1, aes(log(merged1$Reaction_time2)))+geom_histogram()
ggplot(merged1, aes(log(merged1$nlet)))+geom_histogram()



View(stat.desc(1/(merged1$Reaction_time2), basic = FALSE, norm = TRUE))

ggplot(merged1, aes(sample = log(merged1$Reaction_time2)))+stat_qq()+stat_qq_line(colour = "red")

ggplot(merged1, aes(sample = log(merged1$nlet)))+stat_qq()+stat_qq_line(colour = "red")


```
```{r}
cor.test(merged1$Reaction_time2, merged1$nlet, method = "spearman")



cor.test(merged1$Reaction_time2, merged1$X1, method = "spearman")

View(data)




merged2 = filter(merged1, merged1$X1 == 100)
merged3 = filter(merged1, merged1$X1 == 101)

View(merged2)

kok = merged2 %>% group_by(merged2$Condition) %>% summarize(mean(Reaction_time2))

merged3 %>% group_by(merged3$Condition) %>% summarize(mean(Reaction_time2))

t.test(merged2$Reaction_time2 ~ merged2$Condition)
t.test(merged3$Reaction_time2 ~ merged3$Condition)


r1 = sqrt((-0.51613)^2/((-0.51613)^2+16.982))
r2 = sqrt(0.85719^2/(0.85719^2+19.315))


```

